name: Track Tweets

on:
  schedule:
  - cron: "0 11,14 * * *"
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

      - name: Track Tweets
        run: node src/main.js
