name: Track Tweets

on:
  schedule:
    - cron: '0 11 * * *'  # Runs at 11:00 AM UTC every day
    - cron: '0 14 * * *'  # Runs at 2:00 PM UTC every day
    - cron: '0 21 * * *'  # Runs at 10:35 PM UTC every day

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set up variables
        run: |
          echo "BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}" >> $GITHUB_ENV
          echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV
          echo "AUTHOR_ID=${{ secrets.AUTHOR_ID }}" >> $GITHUB_ENV

      - name: Get lastID artifact
        uses: actions/download-artifact@v4
        with: 
          name: lastID-file
        continue-on-error: true

      - name: Create lastID.txt if not exists
        run: |
          if [ ! -f lastID.txt ]; then
            echo "null" > lastID.txt
            echo "lastID.txt created with 'null'"
          else
            echo "lastID.txt already exists."
          fi
  
      - name: Debug
        run: |
          echo "Listing current directory:"
          ls -l
          echo "Contents of lastID.txt:"
          cat lastID.txt || echo "lastID.txt not found"

      - name: Run Script
        run: node src/main.js

      - name: Upload lastID.txt as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lastID-file
          path: lastID.txt
