name: Track Tweets

on:
  schedule:
    - cron: '0 11 * * *'
    - cron: '0 14 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Script
        run: node src/main.js
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          API_KEY:  ${{ secrets.API_KEY}}
          AUTH_DOMAIN:  ${{ secrets.AUTH_DOMAIN }}
          DATABASE_URL:  ${{ secrets.DATABASE_URL }}
          PROJECT_ID:  ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET:  ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID:  ${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID:  ${{ secrets.APP_ID }}
          

  
